#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  mkdir -p "$shome/vendor"
  rm -rf "$shome/vendor/git-crypt"
  git clone git@github.com:AGWA/git-crypt "$shome/vendor/git-crypt"
  cd "$shome/vendor/git-crypt"

  env CPATH="$PKG_HOME/install/include" make
  chmod 755 git-crypt
  mv git-crypt "$shome/bin/"
}

bootstrap
