#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "${DISTRIB_ID}" in
    Darwin)
      brew install git-crypt
      ;;

    Ubuntu)
      ${NOSUDO} sudo apt-get update
      ${NOSUDO} sudo apt-get install -y libssl-dev

      mkdir -p "$shome/vendor"
      rm -rf "$shome/vendor/git-crypt"
      git clone git@github.com:AGWA/git-crypt "$shome/vendor/git-crypt"
      pushd "$shome/vendor/git-crypt"

      env CPATH="$PKG_HOME/install/include" make
      chmod 755 git-crypt
      mv git-crypt "$shome/bin/"
      popd
      rm -rf "$shome/vendor/git-crypt"
      ;;
  esac
}

bootstrap
